[project]
name = "hex-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "pyinstaller>=6.15.0",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.41",
]
